name: Python Tests
on:
  push:
    branches:
      - master

jobs:
  build:
    if: (!contains(github.event.head_commit.message, 'Bump version:'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tests and get coverage using tox
        run: tox
